version: 2.1

jobs:
  
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: The is the build job
          command: echo 'Under construction'
  
  test:
    docker:
      - image: cimg/node:18.7.0
    steps:
      - run:
          name: The is the test job
          command: echo 'Testing, testing'

workflows:
  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - test: 
          filters:
            branches:
              only:
                - dev
